<br><br>

***

<br><br>


<center><font size="7" color="purple">Formats and Sequences</font></center>

<br><br>

***

<br><br>

This and *Python Classes*  and *Python Containers*  are the 3 review documents for generic Python Tech

<br><br>



### Table of Contents

* [Formats](#formats)
    * [Rormat a Row](#rowformats)
    * [Format Numbers](#numbers)
    * [Format a Date](#dates)
* [Strings](#strings)
* [Sequences](#sequences)
    * [Ranges](#range)
    * [For Loops](#forloops)






<br><br>

<center><font size="5" color="blue"><u>Formats</u></font></center><a class="anchor" id="formats"></a>

<br><br>


<br>

The key thing to remember is brackets can contain the referencer (as sprintf uses %) 



<br>
<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Format</th>
      <th>Result</th>
      <th>Comment</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>3.1415926</td>
      <td>{:+.2f}</td>
      <td>+3.14</td>
      <td>Format float 2 decimal places with sign</td>
    </tr>
    <tr>
      <td>5</td>
      <td>{:0>2}</td>
      <td>05</td>
      <td>Pad number with zeros (left padding, width 2)</td>
    </tr>
    <tr>
      <td>100000</td>
      <td>{:,}</td>
      <td>1,000,000</td>
      <td>comma separator</td>
    </tr>
    <tr>
      <td> 0.25</td>
      <td>{:.2%}</td>
      <td>25.00%</td>
      <td>Format percentage</td>
    </tr>
          <tr>
      <td>13</td>
      <td>{:^10d}</td>
      <td>    13    </td>
      <td>Center aligned (width 10)</td>
    </tr>
  </tbody>
</table>




and the *format* method is part of the str class

<br>

In [229]:
print("{:0>5}".format("5"))       # width of 5, right justify, pad with leading zeros

00005


In [22]:
txt="Go Mets !"
format(txt,'*^30')

'**********Go Mets !***********'

<br>

You can define a format at the beginning and use it throughout your script.

<br>

In [230]:

## set user preferred format
num_format = "{:,}".format

## use elsewhere
print(num_format(1000000))
#    1,000,000

1,000,000


In [231]:
principal=12300000
fx = 0.95982621

USD_FORMAT = "${:,.2f}"
EUR_FORMAT = "€{:,.2f}"

print(USD_FORMAT.format(principal), " = ", EUR_FORMAT.format(principal/fx))

$12,300,000.00  =  €12,814,819.88


In [232]:
pi = 3.1415926
precision = 4
print( "{:.{}f}".format( pi, precision ) )

3.1416


In [233]:
txt = "For only {price:.2f} dollars!"
print(txt.format(price = 49))

For only 49.00 dollars!


In [234]:
str = "Oh {0}, {0}! wherefore art thou {0}?".format("Romeo")
print(str)

Oh Romeo, Romeo! wherefore art thou Romeo?


In [235]:
price=49
format(price,">12.3f")

'      49.000'

<br>

The % operator is also an option

<br>


In [236]:
" %0.02f " % price

' 49.00 '

In [237]:
" %s " % price

' 49 '

In [238]:
print(" %s " % price)

 49 


In [239]:
txt1 = "My name is {fname}, I'm {age}".format(fname = "John", age = 36)
print(txt1)

My name is John, I'm 36


In [240]:
myname="Tom"

txt1 = "My name is {}, I'm {}".format(myname, 36)
print(txt1)

My name is Tom, I'm 36


In [241]:
#Use "<" to left-align the value:

txt = "We have {:<8} chickens."
print(txt.format(49))

We have 49       chickens.


In [242]:
#Use ">" to right-align the value:

txt = "We have {:>8} chickens."
print(txt.format(22))

We have       22 chickens.


In [243]:
#Use "^" to center the value:

txt = "We have {:^8} chickens."
print(txt.format(1926))

We have   1926   chickens.


In [245]:
#Use "precision + %" for percent:

txt = "We have {:0.2%} chickens."
print(txt.format(.016))

We have 1.60% chickens.


In [246]:
print('%d %s cost $%.2f' % (6, 'bananas', 1.74))

6 bananas cost $1.74


In [247]:
# Convert integers to float. Note: this time we explictly reference the index 0 and 1 
print ("This site is {0:0.2f}% securely {1}!!".format(100, "encrypted"))

This site is 100.00% securely encrypted!!


In [248]:
# To demonstrate spacing when  strings are passed as parameters 
print("{0:5}, is the computer science portal for {1:8}!".format("GeeksforGeeks", "geeks")) 

GeeksforGeeks, is the computer science portal for geeks   !


In [249]:
# give 6  spaces to each set of values 
print("{:6d} {:6d} {:6d} {:6d}".format(3, 12, 2123, 112234))

     3     12   2123 112234


<br><br>

<font size="4" color="red">Row Formats</font><a class="anchor" id="rowformats"></a>

<br><br>

2 other ways to format rows...

<br><br>

In [12]:
starters = [
    [ 'Andre Iguodala', 4, 3, 7 ],
    [ 'Klay Thompson', 5, 0, 21 ],
    [ 'Stephen Curry', 5, 8, 36 ],
    [ 'Draymon Green', 9, 4, 11 ],
    [ 'Andrew Bogut', 3, 0, 2 ],
]

# define format row
row = "| {player:<16s} | {reb:2d} | {ast:2d} | {pts:2d} |".format

for p in starters:
    print(row(player=p[0], reb=p[1], ast=p[2], pts=p[3]))

| Andre Iguodala   |  4 |  3 |  7 |
| Klay Thompson    |  5 |  0 | 21 |
| Stephen Curry    |  5 |  8 | 36 |
| Draymon Green    |  9 |  4 | 11 |
| Andrew Bogut     |  3 |  0 |  2 |


In [19]:
for p in starters:
    print(p[0].ljust(20), " | ", str(p[1]).center(10), " | ", str(p[2]).rjust(10), " | ")

Andre Iguodala        |      4       |           3  | 
Klay Thompson         |      5       |           0  | 
Stephen Curry         |      5       |           8  | 
Draymon Green         |      9       |           4  | 
Andrew Bogut          |      3       |           0  | 


<br><br>

<font size="4" color="red">Format Dates</font><a class="anchor" id="dates"></a>

<br><br>

<br>

datetime is both a module and a class. You instantiate it and from there you can call its methods.

<br> 

In [251]:
from datetime import datetime

<br>

Take a string and create a datetime instance

<br>

In [252]:
dt_str="2022-07-03"

y = datetime.strptime(dt_str, "%Y-%m-%d")
y

datetime.datetime(2022, 7, 3, 0, 0)

<br> 

Create a datetime instance from the system time

<br>

In [253]:
now = datetime.now()        # class 'datetime.datetime

date_time = now.strftime("%m/%d/%Y, %H:%M:%S")

print("date and time:",date_time)

date and time: 07/03/2022, 11:00:48


<br>

Upper case vs lower case implies full representations vs abbreviated.

<br>

In [254]:
datetime.strftime(y, "%A  %a      %B %b       %D %d      %M %m       %Y     %y")

'Sunday  Sun      July Jul       07/03/22 03      00 07       2022     22'

<br><br>

<font size="4" color="red">Format Numbers</font><a class="anchor" id="numbers"></a>

<br><br>

In [36]:
txt = "The price of the chicken is ${:,.2f}"
print(txt.format(19286))

The price of the chicken is $19,286.00


In [17]:
pi=3.1415926

print("pi = {:+.2f} ".format(pi))     #Format float 2 decimal places with sign
print("pi = +{:.2f} ".format(pi))

myage=19
print("Im = {:} ".format(myage))     # integers dont need anything

print("pi = +{:0>2f} ".format(pi))

txt="I have ${:,}  dollars in my wallet right now"   # money format
print(txt.format(12300000))


txt="But {:.0%} of that is in foriegn currency"   # percent
print(txt.format(.80))

txt="But {:<20.0%} of that is in foriegn currency"   # left justify
print(txt.format(.80))

txt="But {:^20.0%} of that is in foriegn currency"   # enter justify
print(txt.format(.80))


pi = +3.14 
pi = +3.14 
Im = 19 
pi = +3.141593 
I have $12,300,000  dollars in my wallet right now
But 80% of that is in foriegn currency
But 80%                  of that is in foriegn currency


In [42]:
s=1112200000000000000000000000
print(format(s,'E'))      # exponential
print(format(1/s,'E')) 

1.112200E+27
8.991189E-28


<br>

Computers cant accurately store $\frac{1}{3}$ as $.333\bar{3}$ because the 3's stretch to infinity.

<br>

On the other hand, they cant store every possible floating value as a fraction.

<br>

Strings are ineffcient. So are integers. 

<br>

Floats are a datatype that is considered efficient and accurate and handles a wide range of magnitudes. 

<br>

The decimal point *floats* by storing some exponent value that will be raised by base 10.

<br>


<table>
  <thead>
    <tr>
      <th>Significand</th>
      <th>Exponent</th>
      <th>Scientific notation</th>
      <th>Fixed-point value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1.5</td>
      <td>4</td>
      <td>1.5 ⋅ 10<sup>4</sup></td>
      <td>15000</td>
    </tr>
    <tr>
      <td>-2.001</td>
      <td>2</td>
      <td>-2.001 ⋅ 10<sup>2</sup></td>
      <td>-200.1</td>
    </tr>
    <tr>
      <td>5</td>
      <td>-3</td>
      <td>5 ⋅ 10<sup>-3</sup></td>
      <td>0.005</td>
    </tr>
    <tr>
      <td>6.667</td>
      <td>-11</td>
      <td>6.667e-11</td>
      <td>0.00000000006667</td>
    </tr>
  </tbody>
</table>

<br>

Most languages deliberately  handle the formatting for you or provide datatypes like Money or Decimal.

<br>

In [255]:
c = 4 + 1/3

print(c)
print(Decimal(c))  

from decimal import *

with localcontext() as ctx:
    ctx.prec=3
    print(Decimal(c))      
    print(c)

4.333333333333333
4.33333333333333303727386009995825588703155517578125
4.333
4.33333333333333303727386009995825588703155517578125
4.333333333333333


round() negative to specify how many zeroes at the end

In [23]:
c=12345678.87654321
print(round(c,3))
print(round(c,1))
print(round(c,0))
print(round(c,-1))
print(round(c,-3))

12345678.877
12345678.9
12345679.0
12345680.0
12346000.0



<br><br>

<center><font size="5" color="blue"><u>Strings</u></font></center><a class="anchor" id="strings"></a>

<br><br>

<br>

Type `dir(str)`  to see all methods of the str class.

- `capitalize()`  CAPITALIZES THE FIRST 
- `title()`  CAPITALIZES EACH WORD
- `upper()`   CAPITALIZES EVERY LETTER

- `format()`
- `strip()`    ALSO LSTRIP AND RSTRIP...
- `replace()`
- `join()`         COLLAPSE AN ARRAY TO A SING STRING

- `isnumeric()`        RETURNS TRUE OR FALSE
- `startswith()`
- `endswith()`

<br>


In [7]:
txt="the rain in spain falls manly on the plain"

txt.replace("manly","mainly")

'the rain in spain falls mainly on the plain'

In [258]:
txt[0].upper()

'T'

In [259]:
txt.capitalize()         # capitalize the first 

'The rain in spain falls manly on the plain'

In [260]:
txt.title()             # capitalize every word 

'The Rain In Spain Falls Manly On The Plain'

In [261]:
txt.upper()            # capitalize every letter

'THE RAIN IN SPAIN FALLS MANLY ON THE PLAIN'

<br>

The translate function 

<br>

In [9]:
remap = { 
            ord('a') : 'XX',
            ord(' ') : '_',
            ord('n') : None   # remove
         }

txt.translate(remap)

'the_rXXi_i_spXXi_fXXlls_mXXly_o_the_plXXi'

<br>

The join function 

<br>

In [20]:
words = ['The','Rain','In','Maine']
' '.join(words)

'The Rain In Maine'

In [10]:
txt="00000329"
txt.lstrip('0')        # remove leading zeros

'329'

<br>
<br><br>

<font size="4" color="red">The Regex Class (re)</font><a class="anchor" id="re"></a>

<br><br>

In [262]:
import re

txt="the rain in spain"

re.split(" ", txt)

['the', 'rain', 'in', 'spain']

In [263]:
x = re.search("^the.*spain$", txt)      # re.Match object;
x

<re.Match object; span=(0, 17), match='the rain in spain'>

In [264]:
# return the position of the search
x = re.search("\s", txt)
print("The first white-space character is located in position:", x.start())


The first white-space character is located in position: 3


In [265]:
# substitute ( replace ) space with 9
x = re.sub("\s", "9", txt)
x

'the9rain9in9spain'

In [266]:
txt="23, 32, 67, 00,99"

re.split(",", txt)

['23', ' 32', ' 67', ' 00', '99']

<br>

strings are iterable, you can reference by index

<br>

In [267]:
app_str="apple"
for x in range(len(app_str)):
  print(app_str[x], end="-")

a-p-p-l-e-

In [268]:
new_txt=txt+"!"
print(new_txt)

23, 32, 67, 00,99!


<br>

"r" notation to interpret backslashes as strings

<br>

"f" notation to translate non string to string

In [285]:
path=r'C:\_InProgress\BackUp\\'
print("path is " + path )
num=15
print("number is " + f'num')

path is C:\_InProgress\BackUp\\
number is num


<br>

the <b><u>codecs</u></b> and <b><u>unicodedata</u></b> modules help with non-ascii characters

<br><br><br><br>


<br><br>

<center><font size="5" color="blue"><u>Sequences</u></font></center><a class="anchor" id="sequences"></a>

<br><br>

<font size="4" color="red">range arange linspace</font><a class="anchor" id="range"></a>

<br><br>


<br>

*range* works ok for for loops

<br>


In [269]:
x = range(3) 
for y in x:
    print(y, end= " ")


0 1 2 

In [270]:
np.sort(np.random.randn(10))

array([-1.69673061, -1.68719022, -1.33079786, -0.50704508, -0.10992157,
        0.26971566,  0.39473315,  0.62329665,  0.80784299,  1.67293077])

<br>

The typical parameters for *linspace* are start,stop,num. Returns a numpy.ndarray

num is the <font size="4"><b><i>number of steps</i></b></font>

<br>

In [271]:
np.linspace(1,3,5)         # i dont know what the step size is, i just know i want 5 steps

array([1. , 1.5, 2. , 2.5, 3. ])

<br>

The typical parameters for *arange* are start,stop,step. Returns a numpy.ndarray

step is the <font size="4"><b><i>size of the step</i></b></font>

<br>

note this is equivalent to `range(1,12,2)`

<br>

In [272]:
np.arange(1,12,2)       # i dont know how many steps i need i just know i want to step by 2

array([ 1,  3,  5,  7,  9, 11])

<br><br>

<font size="4" color="blue">For Loops</font><a class="anchor" id="forloops"></a>

<br><br>

You can loop thru numpy arrays, tuples, lists, etc..

In [273]:
fruits = ["apple", "banana", "cherry"]    # list
for x in fruits:
  print(x, end=" , ")

apple , banana , cherry , 

In [274]:
for x in np.arange(1,12,2):
  print(x, end=" , ")

1 , 3 , 5 , 7 , 9 , 11 , 

<br>
even a string
<br>

In [275]:
for x in "banana":          
  print(x, end="-")

b-a-n-a-n-a-

<br>
The range function is your basic for x = 1 to 10 construct but note the default is 0 thru n-1
<br>

In [276]:
for i in range(5):
    print(i, end=",")

0,1,2,3,4,

In [277]:
for i in range(1,11):       # for x = 1 to 10
    print(i, end=",")

1,2,3,4,5,6,7,8,9,10,

In [278]:
for i in range(1,12,2):       # for x = 1 to 10
    print(i, end=",")

1,3,5,7,9,11,

<br>

above is equivalient to np.arange(1,12,2)

<br>

range and arange may seem similar. 
<pre>
    arange returns an numpy array so each step is stored in memory
    range returns a range (iterator) object. (each step is not in memory)
    arange has some extra controls, you can specify dtype=float
</pre>

<br>


<br><br>

continue and break and pass are all keywords to continue, break and pass

<br><br>

In [279]:
for letter in 'hey':
    pass
print('Last Letter :', letter)

Last Letter : y


<br>

for loops and while loops are essentially wrappers over the iter() and next() functions that operate
on *iterable* objects, which include lists, tuples, sets, dictionaries and strings

<br>